In [1]:
import numpy as np
import pandas as pd
from rat import ratmath

# Extract Some Data

In [2]:
df_a = pd.read_csv('tables/employment.csv')
df_a.head()

District  Agriculture  Light industry  Heavy industry  Service sector
0  Dmitrov          584             952             562             355
1     Klin          615             733             761              29
2  Kolomna          968             415             441              56
3  Orehovo          202             204             142             807
4     Ruza          360              96             919             191

In [3]:
df_b = pd.read_csv('tables/environment.csv')
df_b.head()

District  Urban  Suburban  Rural
0  Dmitrov   1835       371    247
1     Klin   1531       474    133
2  Kolomna   1209       550    121
3  Orehovo    946        28    381
4     Ruza    999       506     61

# ratmath.py

In [4]:
lines_a = ratmath.get_lines(df_a, name_cols=['District'])
lines_a

array([[584, 562, 952, 355],
       [615, 761, 733,  29],
       [968, 441, 415,  56],
       [202, 142, 204, 807],
       [360, 919,  96, 191],
       [880, 382, 119,  86]])

In [5]:
lines_b = ratmath.get_lines(df_b, name_cols=['District'])
lines_b

array([[ 247,  371, 1835],
       [ 133,  474, 1531],
       [ 121,  550, 1209],
       [ 381,   28,  946],
       [  61,  506,  999],
       [ 380,  473,  614]])

In [6]:
line_a, line_b = lines_a[0], lines_b[0]

In [8]:
ratmath.get_system(line_a, line_b)

(array([[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0],
        [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
        [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1]]),
 array([ 584,  562,  952,  355,  247,  371, 1835]))

In [9]:
ratmath.get_problem(line_a, line_b)

(Problem(Minimize(Expression(CONVEX, NONNEGATIVE, ())), [Equality(Expression(AFFINE, NONNEGATIVE, (6,)), Constant(CONSTANT, NONNEGATIVE, (6,)))]),
 Variable((12,), nonneg=True))

In [12]:
ratmath.restore_line(line_a, line_b, print_status=True)

Status:  optimal_inaccurate
The optimal value is 1040756.7346880854
A solution x is
[ 35.2463141   77.42548429 487.3720543   27.848913    70.0280832
 479.9746532  158.98465972 201.16382991 611.11039992   8.77090225
   7.39409902 347.27872693] 



array([ 35.2463141 ,  77.42548429, 487.3720543 ,  27.848913  ,
        70.0280832 , 479.9746532 , 158.98465972, 201.16382991,
       551.51228007,   8.77090225,   7.39409902, 347.27872693])